[package]
authors = ["KirmesBude <kirmesbude@gmail.com>"]
name = "bevy_titan"
version = "0.2.0"
edition = "2021"
description = "Bevy plugin for spritesheet manifest loading"
repository = "https://github.com/KirmesBude/bevy_titan"
license = "MIT OR Apache-2.0"
keywords = ["gamedev", "bevy", "spritesheet", "textureatlas", "assets"]
categories = ["game-development"]
readme = "README.md"
exclude = ["/assets"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.10", default-features = false, features=["bevy_asset", "bevy_render", "bevy_sprite"]}
serde = { version = "1", features = ["derive"] }
ron = "0.8.0"

[dev-dependencies]
bevy = "0.10"

[[example]]
name = "spritesheet"
path = "examples/spritesheet.rs"
